#101 создание кнопки `связаться с нами`
Studio-Yandex-Practicum/maxboom_frontend pull request #129
Opened 2023-12-07 15:48 UTC by Sibisov-Artem

2023-12-11 11:46 UTC, aimenin requested changes
Отличная работа!
Парочка помарок

2023-12-11 11:46 UTC, aimenin commented on src/entities/СontactCard/СontactCard.tsx
> +const ContactCard: FC<PropsContactCard> = ({ messenger, Icon }) => {
к компоненту добавляем документацию, можешь посмотреть как это сделано в других компонентах

2023-12-11 11:46 UTC, aimenin commented on src/entities/СontactCard/СontactCard.tsx
> +
пустая строчка

2023-12-11 11:46 UTC, aimenin commented on src/entities/СontactCard/СontactCard.tsx
> +        <p className={styles.text}>{messenger.title}</p>
вместо p используем нашу типографику

2023-12-11 11:46 UTC, aimenin commented on src/entities/СontactCard/СontactCard.tsx
> +
давай не будем оставлять пустых строчек в jsx

2023-12-11 11:46 UTC, aimenin commented on src/features/Contacts/Contacts.tsx
> +const Contacts: FC<PropsContacts> = ({ messenger }) => {
здесь опять же документация

2023-12-14 00:13 UTC, Sibisov-Artem commented on src/entities/СontactCard/СontactCard.tsx
> +const ContactCard: FC<PropsContactCard> = ({ messenger, Icon }) => {
Добавлена документация: https://github.com/Studio-Yandex-Practicum/maxboom_frontend/commit/73f51f8c5c53f879e48e77fb57a33eecd88af49a

2023-12-14 00:14 UTC, Sibisov-Artem commented on src/entities/СontactCard/СontactCard.tsx
> +
поправил

2023-12-14 00:15 UTC, Sibisov-Artem commented on src/entities/СontactCard/СontactCard.tsx
> +
ОК.  Поправил

2023-12-14 00:39 UTC, Sibisov-Artem commented on src/entities/СontactCard/СontactCard.tsx
> +        <p className={styles.text}>{messenger.title}</p>
Поправил - https://github.com/Studio-Yandex-Practicum/maxboom_frontend/commit/3233e02283b121541e27277602faea2cfe8fef96

2023-12-14 00:46 UTC, Sibisov-Artem commented on src/features/Contacts/Contacts.tsx
> +const Contacts: FC<PropsContacts> = ({ messenger }) => {
Добавлена документация:
https://github.com/Studio-Yandex-Practicum/maxboom_frontend/commit/cd7b52cee6734a2f1ab04aed791bbe0eb5bea16f

2023-12-15 09:44 UTC, aimenin approved these changes
👍

2023-12-15 10:00 UTC, merged