переделать компонент footer под FSD
Studio-Yandex-Practicum/maxboom_frontend pull request #169
Opened 2023-12-25 21:10 UTC by ArturKhelshtein

перенесен компонент Footer в `widgets`
перенесен компонент SubscribeFormв `entities`
перенесены компоненты Logo, icons(вероятно дальше удалить надо будет)  в `shared`

сделаны моки для получения данных с сервера для футера и хедера

2024-01-08 08:42 UTC, Segodnya requested changes
Посмотрел. Мне кажется есть что можно поправить. Ребята посмотрят и может еще чего найдут

2024-01-08 08:42 UTC, Segodnya commented on src/entities/SubscribeForm/SubscribeForm.tsx
import { type FC, type FormEvent } from 'react'

2024-01-08 08:42 UTC, Segodnya commented on src/entities/SubscribeForm/SubscribeForm.tsx
> +      <span className={`${styles.caption}`}>
Давай уберем эти стрёмные обратные кавычки там, где они не нужны, чтоб код чище был

2024-01-08 08:42 UTC, Segodnya commented on src/entities/SubscribeForm/SubscribeForm.tsx
> +      <span className={`${styles.caption}`}>
Я бы в целом предложил с помощью classnames значительно упростить стилизацию тут и повысить читаемость. Типа такого:
const labelClassName = classNames({
    [styles.label_footer]: type === 'footer',
    [styles.label_subscribe]: type === 'subscribe',
  });

  const formClassName = classNames({
    [styles.form_footer]: type === 'footer',
    [styles.form_subscribe]: type === 'subscribe',
  });

  const containerClassName = classNames(styles.container, {
    [styles.container_footer]: type === 'footer',
    [styles.container_subscribe]: type === 'subscribe',
    [className]: className,
  });
  
  className={containerClassName}
  className={classNames(styles.label, labelClassName)}
  className={classNames(styles.form, formClassName)}

2024-01-08 08:42 UTC, Segodnya commented on src/shared/ui/logo/Logo.tsx
> +import { FC } from 'react'
```suggestion
import { type FC } from 'react'
```

2024-01-08 08:42 UTC, Segodnya commented on src/shared/ui/logo/Logo.tsx
> +    <div className={`${styles.container}`}>
тоже обратные кавычки ни к чему здесь совсем, можно убрать

2024-01-08 08:42 UTC, Segodnya commented on src/widgets/Footer/Footer.tsx
> +console.log(coreBaseData.footer)
ой-ёй :) давай уберём

2024-01-09 09:17 UTC, aimenin requested changes
Можно выделить компонент
Добавить storybook для новых компонентов

2024-01-09 09:17 UTC, aimenin commented on src/widgets/Footer/Footer.tsx
> +                <li className={styles['footer__payment-nav']} key={logo.title}>
можно выделить в компонент

2024-01-09 12:45 UTC, ArturKhelshtein commented on src/entities/SubscribeForm/SubscribeForm.tsx
примеры смотрел, там было без ’type' поискал, нашел ответ только у chatGpt «import { type FC }: В TypeScript до версии 3.8, для объявления типов использовалось ключевое слово type. import { type FC } подразумевает, что FC является типом, который был объявлен в модуле React и экспортирован с использованием type. Отметим, что начиная с TypeScript 3.8, type стало необязательным для объявления типов, и теперь можно объявлять типы без его использования. Таким образом, если вы используете новые версии TypeScript и React, import { FC } будет более предпочтительным способом импорта типа функционального компонента React.»

2024-01-09 13:06 UTC, ArturKhelshtein commented on src/entities/SubscribeForm/SubscribeForm.tsx
> +      <span className={`${styles.caption}`}>
прошу пояснений к части classNames @Segodnya

2024-01-09 14:22 UTC, ArturKhelshtein commented on src/entities/SubscribeForm/SubscribeForm.tsx
> +      <span className={`${styles.caption}`}>
*замечание принято, будет занесено в лист исправлений. в данном PR этот компонент не менялся (только импорты)

2024-01-11 16:18 UTC, aimenin approved these changes
👍

2024-01-11 18:15 UTC, Segodnya approved these changes
👍. Я уже вмержил обновленный header с выделенной фичей поиска в мастер. поэтому когда будешь разрешать конфликт будь внимательней. если будут вопросы что/как расконфликтить - пиши :)

2024-01-11 18:20 UTC, Segodnya commented
search выпилен и вместо него SearchProduct
а Logo лучше оставить твое, думаю

2024-01-11 19:22 UTC, merged