#176 bugfix: исправление бага недоступности воздействия на область под скрытым меню контактов
Studio-Yandex-Practicum/maxboom_frontend pull request #178
Opened 2023-12-29 06:11 UTC by Sibisov-Artem

Скрытый компонент менюшек с контактами перекрывал под собой область, что делало невозможным взаимодействие с другими компонентами, скрытыми под ним:

![image](https://github.com/Studio-Yandex-Practicum/maxboom_frontend/assets/119536151/98b1af5c-d2fb-4f46-ace6-ac02396acbd0)

+ исправлено наименование компонента СontactCard (начиналось на русскую букву С) и его папки местоположения

2024-01-08 08:23 UTC, Segodnya requested changes
Добавить classnames для условного выбора стилей

2024-01-08 08:23 UTC, Segodnya commented on src/features/Contacts/Contacts.tsx
> +        className={
в проекте есть либа classnames, я бы здесь переписал используя ее:

const contactsMenuClasses = classNames(styles.contactsMenu, {
    [styles.contactsMenuHidden]: !messageMenuActive,
  });

className={contactsMenuClasses}

2024-01-08 10:49 UTC, Sibisov-Artem commented on src/features/Contacts/Contacts.tsx
> +        className={
Круто, спасибо!

2024-01-09 08:59 UTC, aimenin approved these changes
👍

2024-01-11 18:13 UTC, Segodnya approved these changes
👍

2024-01-13 12:00 UTC, merged