Переделка компонента Бренды по fsd #149
Studio-Yandex-Practicum/maxboom_frontend pull request #179
Opened 2024-01-07 11:20 UTC by Sibisov-Artem

Переделать компонент бренды по fsd
 Переделать интерфейс компонента с учетом того, что мы можем получить с бекенда
 Переделать моки с учетом схемы с бекенда

2024-01-09 08:58 UTC, aimenin requested changes
Перенести компонент из папки ui

2024-01-09 08:58 UTC, aimenin commented on src/shared/ui/BrandCard/BrandCard.tsx
> +          <Img
мы не можем использовать в ui компоненты из ui -> значит мы переносим этот компонент на другой уровень

2024-01-09 08:58 UTC, aimenin commented on src/shared/ui/BrandCard/BrandCard.tsx
> +            width={card.width ?? '150'}
150 в константу

2024-01-09 09:13 UTC, aimenin commented
Добавить storybook для компонентов

2024-01-09 09:34 UTC, Sibisov-Artem commented on src/shared/ui/BrandCard/BrandCard.tsx
> +          <Img
ОК, перенесу в entities. 
Я могу еще с этим PR перенести Img в shared/ui? Сейчас он находится в src/ui/img/

2024-01-11 16:13 UTC, aimenin approved these changes
Отлично, только не забудь либо в этом pr либо в другом для компонентов сделать storybook

2024-01-17 09:08 UTC, aimenin approved these changes
👍

2024-01-17 09:48 UTC, merged