#182-bug-fix-CartPage
Studio-Yandex-Practicum/maxboom_frontend pull request #184
Opened 2024-01-16 06:39 UTC by JuliaAvramenko

Исправила ошибки, а также добавила Storybook к компонентам

2024-01-17 09:02 UTC, aimenin commented
Ссылка на issue, без ссылки issue само не закроется

2024-01-17 09:07 UTC, aimenin requested changes
Что то непонятное с ButtonDots

2024-01-17 09:07 UTC, aimenin commented on src/features/CartEdit/ui/CartEdit/CartEdit.tsx
> +        <ButtonDots className={styles.button_dots} isMenuOpen={needToOpenContextMenuButtonDots}>
я зашел в компонент ButtonDots и он не принимает children, не понимаю тогда констурукции

2024-01-18 10:05 UTC, JuliaAvramenko commented on src/shared/ui/ButtonDots/ButtonDots.tsx
> +        {isMenuOpened && <div ref={refContextMenu}>{children}</div>}
тут мы прокидываем children, они прокидываются только если нужно открыть контекстное меню @aimenin

2024-01-18 15:29 UTC, aimenin approved these changes
👍

2024-01-19 13:43 UTC, merged