Enhancement 139 blog fsd
Studio-Yandex-Practicum/maxboom_frontend pull request #190
Opened 2024-01-22 15:43 UTC by Korvin22

Переиспользованы заголовки, параграфы, ссылки, кнопки по fsd.

2024-01-23 10:03 UTC, ArturKhelshtein reviewed
вроде изменения ок. Но почему не разнесено по папкам FSD, BlogCategories: components → Entities

2024-01-24 14:09 UTC, aimenin commented
Нет ссылки на issue

2024-01-24 14:09 UTC, aimenin requested changes
Какая задача решалась здесь?
Блог с категориями не разбит по fsd

2024-01-25 15:09 UTC, aimenin requested changes
Практически все, отличная работа!
Остались комментарии по двум компонентам

2024-01-25 15:09 UTC, aimenin commented on src/components/BlogItemForContainer/BlogItemForContainer.tsx
Почему этот компонент остался в папке components, а не переехал в соответствующую папку по fsd?

2024-01-25 15:09 UTC, aimenin commented on src/components/BlogMain/BlogMain.tsx
К этому компоненту такой же вопрос

2024-02-04 12:50 UTC, aimenin requested changes
Комментарии, console log

2024-02-04 12:50 UTC, aimenin commented on src/components/BlogMain/BlogMain.tsx
Этот компонент почему остался в components?
Он используется?

2024-02-04 12:50 UTC, aimenin commented on src/entities/BlogCategories/BlogCategories.tsx
> +  const filterCategories = (curcat: string, cards: TBlogItem[]) => {
эту функцию можно вынести из компонента в utils

2024-02-04 12:50 UTC, aimenin commented on src/entities/BlogMain/BlogMain.tsx
> +/*import { TBlogItem } from '@/models/BlogItemModel'*/
нужен комментарий?

2024-02-04 12:50 UTC, aimenin commented on src/entities/BlogMain/BlogMain.tsx
> +    // ...
нужен комментарий?

2024-02-04 12:50 UTC, aimenin commented on src/entities/BlogMain/BlogMain.tsx
> +  console.log(setItems)
console.log

Линтером проверяем код перед тем как отправлять на ревью

2024-02-04 12:50 UTC, aimenin commented on src/entities/BlogMain/BlogMain.tsx
> +  const [itemNumber, setItemNumber] = useState(9)
9 и 1 в константы, в коде магические числа не держим

2024-02-04 12:50 UTC, aimenin commented on src/entities/BlogTags/BlogTags.tsx
> +  /*const [items, setItems] = useState();*/
убираем комментарий

2024-02-04 12:50 UTC, aimenin commented on src/entities/BlogTags/BlogTags.tsx
> +    console.log(newItems)
console.log

2024-02-04 12:50 UTC, aimenin commented on src/entities/BlogTags/BlogTags.tsx
> +  const filterTags = (curcat: string, cards: TBlogItem[]) => {
выносим такие функции из тела компонента

2024-03-18 15:36 UTC, closed without merging