Enhancement 186 modal callback
Studio-Yandex-Practicum/maxboom_frontend pull request #198
Opened 2024-01-24 21:48 UTC by ArturKhelshtein

- добавлено модальное окно в футере по нажатию «обратный звонок»
- подправлена верска быстрого заказа
- реализовано закрытие по «х» на форме, из-за чего ранние вхождения модального окна пришлось дополнить
- поправлены опечатки

2024-01-25 15:03 UTC, aimenin requested changes
Исправить парочку замечаний

Так же для новых компонентов делаем storybook

2024-01-25 15:03 UTC, aimenin commented on src/features/CallBack/ui/CallBack/CallBack.tsx
> +            <span className={styles.span}>*</span> Ваше имя:
span звездочка в shared -> ui

2024-01-25 15:03 UTC, aimenin commented on src/widgets/Footer/Footer.tsx
> +              <p className={styles['footer__support-text']}>Поддержка</p>
используем типографику

2024-01-25 15:03 UTC, aimenin commented on src/widgets/Footer/Footer.tsx
> +              <p className={styles.footer__caption}>{coreBaseData.footer.company_info}</p>
используем типографику

2024-01-25 15:03 UTC, aimenin commented on src/widgets/Footer/Footer.tsx
> +                <p className={styles.footer__hours}>{coreBaseData.footer.support_work_time}</p>
используем типографикуу

2024-01-25 20:12 UTC, ArturKhelshtein commented on src/features/CallBack/ui/CallBack/CallBack.tsx
> +          <div className={styles['cross-button']}>
можно, обертка для того что бы наводить можно было не только непосредственно на обводку крестик но и на виртуальный прямоугольник.

2024-01-26 14:26 UTC, aimenin approved these changes
👍

2024-01-26 16:50 UTC, merged