#210-api-inserted-to-StoriesBlock
Studio-Yandex-Practicum/maxboom_frontend pull request #228
Opened 2024-02-05 10:52 UTC by JuliaAvramenko

2024-02-07 11:09 UTC, aimenin requested changes
Парочка замечаний.
Плюс обрати внимание, что Артур добавил правила импортирования.
Смержи мейн себе в ветку и реши конфликты

2024-02-07 11:09 UTC, aimenin commented on src/entities/StoryCard/StoryCard.tsx
> +      <img src={pictures[0]} alt="история" className={styles.img} draggable="false" />
нужна проверка на существование нулевого элемента в массиве иначе рендерим пустую картинку

2024-02-07 11:09 UTC, aimenin commented on src/entities/StoryCard/StoryCard.tsx
>   * @param {TCard} card - параметры карточки из группы историй
не обновлена документация

2024-02-07 11:09 UTC, aimenin commented on src/widgets/StoriesBlock/model/slice/storiesSlice.ts
> +        state.isLoading = false
когда обрабатываем ошибку в стор кладем эту самую ошибку, либо в сторе храним поле false типа boolean, есть ли ошибка или нет.
Иначе эта проверка на rejected бессмысленная

2024-02-10 09:00 UTC, JuliaAvramenko commented
Исправила баги в компоненте  и исправила некоторые баги по api в других помпонентах, которые я делала

2024-02-11 13:22 UTC, aimenin approved these changes
Перед тем как смерджить - нужно исправить то, что советует github actions

2024-02-11 13:22 UTC, aimenin commented on src/entities/StoryCard/StoryCard.module.scss
> +  max-width: 160px;
В чем смысл одинаковой max-width и min-width, а не использования width?

2024-02-11 13:22 UTC, aimenin commented on src/entities/StoryCard/StoryCard.module.scss
> +
пустая строчка

2024-02-25 16:15 UTC, aimenin commented
@JuliaAvramenko Решаем конфликты и мержим pr

2024-02-28 10:36 UTC, merged