#211-product-card-in-fsd
Studio-Yandex-Practicum/maxboom_frontend pull request #232
Opened 2024-02-09 14:24 UTC by MargaritaShumilina

Компонент товара из каталога был переведен по FSD

2024-02-11 13:07 UTC, aimenin commented
В development ссылку на решаемый issue
В assignee назначем себя
В milestone пул реквесты не назначаем

2024-02-11 13:18 UTC, aimenin requested changes
1. В переделанных компонентах использовать типографику.
2. В компоненте ProductLabels, насколько я понял, не прописан storybook

2024-02-11 13:18 UTC, aimenin commented on src/features/WidgetButtonsFunctions/WidgetButtonsFunctions.tsx
> +// import styles from '../ProductCard/ProductCard.module.scss'
нужен комментарий?

2024-02-11 13:18 UTC, aimenin commented on src/pages/ProductsPage/ProductsPage.tsx
> +                // <ProductCard key={index} layout={cardView} onEyeClick={changeModalState} />
нужен комментарий?

2024-02-15 11:25 UTC, MargaritaShumilina commented
- Добавлены storybook для ProductLabels, WidgetButtonsFunctions и WidgetButtonsPurchase;
 - Убраны лишние комментарии;
 - Использована типографика в ProductItem

2024-02-16 12:02 UTC, aimenin approved these changes
Нужно порешать конфликты в остальном можно мержить

2024-02-19 12:08 UTC, merged