#193-create-category-card-component
Studio-Yandex-Practicum/maxboom_frontend pull request #233
Opened 2024-02-11 11:13 UTC by Kseniya554

2024-02-11 13:01 UTC, aimenin commented
1. В ревьюеры меня
2. В Assignee себя
3. В development ссылку на решаемый issue
4. В описание pr - что было сделано

2024-02-11 13:06 UTC, aimenin requested changes
1. Типографика
2. Нет сторибука для нового компонента

2024-02-11 13:06 UTC, aimenin commented on src/components/CategoryCard/CategoryCard.tsx
> +      <p className={styles['category-card__text']}>FM-трансмиттеры</p>
используем нашу типографику

2024-02-12 10:31 UTC, ArturKhelshtein reviewed
вопрос зачем изменять форматирование в файлах которые не относятся к задаче.

2024-02-12 10:31 UTC, ArturKhelshtein commented on src/assets/icons/IconArrow.tsx
следует переносить используемы компоненты согласно FSD

2024-02-12 10:31 UTC, ArturKhelshtein commented on src/components/CategoryCard/CategoryCard.tsx
папка components исключается согласно FSD. Не надо создавать новые компоненты в этой папке. Необходимо CategoryCard перенести в /Entities или /Widgets

2024-02-14 17:32 UTC, Kseniya554 commented on src/components/CategoryCard/CategoryCard.tsx
Хорошо, сейчас буду переделывать.
По поводу изменения форматирования в других файлах, которые не относятся к задаче, сейчас всё вернула, как было. А отформатировалось, поскольку прописала команду "npm run format", видимо не надо было этого делать.

2024-02-25 16:14 UTC, aimenin requested changes
Не тот роут для страницы все категории

2024-02-25 16:14 UTC, aimenin commented on src/app/router/AppRouter/ui/AppRouter.tsx
> +        element: <CategoryPage />
Страница категорий не находится по этому роуту, тут находится страница продуктов какой то одной категории, а не всех

2024-02-25 19:32 UTC, Kseniya554 commented on src/app/router/AppRouter/ui/AppRouter.tsx
> +        element: <CategoryPage />
Хорошо, поменяю, тогда может прописать роут /all-categories? И верну на место  <ProductsPage />

2024-02-27 08:27 UTC, aimenin approved these changes
Парочка замечаний по стилям, в остальном можно мержить

2024-02-27 08:27 UTC, aimenin commented on src/entities/CategoryCard/CategoryCard.module.scss
> +  margin-top: 16.599px;
элементы лежат во flex контейнеры, значит позиционировать их можно с помощью свойства gap

2024-02-27 08:27 UTC, aimenin commented on src/entities/CategoryCard/CategoryCard.module.scss
> +  width: 222.44px;
такие значения можно и нужно округлять

2024-02-27 11:46 UTC, Kseniya554 commented on src/entities/CategoryCard/CategoryCard.module.scss
> +  margin-top: 16.599px;
> элементы оставляют во гибких контейнерах, то есть позиционировать их можно с помощью свойств разрыва

Не совсем понятен этот комментарий. Имеешь ввиду использование свойства flex-wrap: wrap; ?Его думала использовать во время вёрстки всех категорий.

2024-02-27 11:46 UTC, Kseniya554 commented on src/entities/CategoryCard/CategoryCard.module.scss
> +  width: 222.44px;
Сейчас подправлю

2024-03-04 14:11 UTC, merged