#137-enhancement-Slider-changed-to-fsd
Studio-Yandex-Practicum/maxboom_frontend pull request #235
Opened 2024-02-14 16:37 UTC by JuliaAvramenko

2024-02-16 11:53 UTC, aimenin requested changes
Переносим компонент slider

2024-02-16 11:53 UTC, aimenin commented on src/shared/ui/Slider/Slider.tsx
> +const Slider: FC<TProps> = ({ children, className }) => {
не думаю, что это кладем в shared, потому что здесь используем компоненты из shared

2024-02-16 11:53 UTC, aimenin commented on src/shared/ui/Slider/Slider.tsx
> +const Slider: FC<TProps> = ({ children, className }) => {
Думаю это в features

2024-02-25 16:12 UTC, aimenin requested changes
Парочка вопросов и замечаний, основное - использовать нашу типографику в SliderCard

2024-02-25 16:12 UTC, aimenin commented on src/entities/SliderCard/SliderCard.tsx
> +          <p className={styles.item__info}>{title}</p>
почему не наша типографика используется?

2024-02-25 16:12 UTC, aimenin commented on src/entities/SliderInfo/SliderInfo.stories.tsx
> +// import Img1 from '@/assets/images/stories/img-stories-01.png'
нужен коммент?

2024-02-25 16:12 UTC, aimenin commented on src/features/Slider/Slider.tsx
> +  children: React.ReactNode[]
насколько знаю в FC уже есть children и их можно самому не типизировать + у тебя children типизируются как массив, но может прийти и один элемент

2024-02-25 16:12 UTC, aimenin commented on src/features/Slider/Slider.tsx
> +  className?: string
в FC classname тоже должен быть

2024-02-25 16:12 UTC, aimenin commented on src/features/Slider/Slider.tsx
> +  function changeSlide(direction: 'prev' | 'next') {
prev и next можно в enum положить, чтобы удобно к ним в компоненте обращаться

2024-02-25 16:12 UTC, aimenin commented on src/pages/MainPage/MainPage.tsx
> +
нужна пустая строчка?

2024-02-25 16:12 UTC, aimenin commented on src/shared/ui/ArrowButton/ArrowButton.tsx
> +const ArrowButton: FC<TProps> = ({ type, className, ...props }) => {
А в чем отличие этого компонента от обычной кнопки с иконкой внутри?

2024-02-28 11:12 UTC, JuliaAvramenko commented on src/features/Slider/Slider.tsx
> +  className?: string
Не совсем поняла комментарий

2024-02-28 14:45 UTC, JuliaAvramenko commented on src/features/Slider/Slider.tsx
> +  children: React.ReactNode[]
мне кажется, даже если прийдет один элемент, то он должен быть в массиве? вообще это по api нужно смотреть , что должно приходить, я бы согласилась с тем, что есть в массиве 1 элемент, тогда Slider не нужно показывать

2024-02-28 19:57 UTC, JuliaAvramenko commented on src/features/Slider/Slider.tsx
> +  children: React.ReactNode[]
я сделала перевод того, что прийдет в children, в массив

2024-03-04 13:47 UTC, aimenin approved these changes
Отличная работа, парочка предложений по улучшениям, в остальном все отлично

2024-03-04 13:47 UTC, aimenin commented on src/features/Slider/Slider.tsx
> +export enum Direction {
я бы вынес это в Slider/model/types.ts

2024-03-04 13:47 UTC, aimenin commented on src/features/Slider/Slider.tsx
> +  className?: string
FC<PropsWithChildren<TProps>> - FC это тоже тип, в нем уже прописаны className, children и тд

2024-03-04 13:47 UTC, aimenin commented on src/features/Slider/Slider.tsx
> +  function changeSlide(direction: Direction) {
эту функцию я бы тоже вынес в model/utils.ts

2024-03-04 13:47 UTC, aimenin commented on src/features/Slider/Slider.tsx
> +            return (
это можно вынести в компонент отдельный, положить в Slider/ui

2024-03-04 17:59 UTC, JuliaAvramenko commented on src/features/Slider/Slider.tsx
> +  function changeSlide(direction: Direction) {
Не стала, так как функция имеет много зависимостей

2024-03-04 18:32 UTC, merged