№222 create form return
Studio-Yandex-Practicum/maxboom_frontend pull request #240
Opened 2024-02-22 12:24 UTC by Evgenii959

Создал заново ветку. Исправил ошибки которые были. Сделал чекбокс в стори.

2024-02-25 15:59 UTC, aimenin requested changes
Не понятно зачем изменен конфиг сторибука + маленькие замечания

2024-02-25 15:59 UTC, aimenin commented on .storybook/main.ts
почему изменены файлы настройки сторибука?

2024-02-25 15:59 UTC, aimenin commented on package.json
> +    "@storybook/test": "^7.6.16",
что это за пакет и почему об этом нет ничего в описании

2024-02-25 15:59 UTC, aimenin commented on src/pages/DeliveryPage/DeliveryPage.tsx
> +const DeliveryPage = () => {
документация оставляем для всех компонентов

2024-02-25 15:59 UTC, aimenin commented on src/pages/HelpPage/HelpPage.tsx
> +const HelpPage = () => {
здесь тоже оставляем документаци.

2024-02-25 15:59 UTC, aimenin commented on src/pages/HelpPage/HelpPage.tsx
> +import Heading, { HeadingType } from '@/shared/ui/Heading/Heading'
порядок импортов не соблюден

2024-02-25 15:59 UTC, aimenin commented on src/shared/ui/Checkbox/Checkbox.tsx
> +// Checkbox.tsx
комменты не оставляем

2024-02-25 15:59 UTC, aimenin commented on src/shared/ui/Checkbox/Checkbox.tsx
> +export interface CheckboxProps {
из типов в компоненте храним только пропсы

2024-02-25 15:59 UTC, aimenin commented on src/shared/ui/Checkbox/Checkbox.tsx
> +  // Используем хук useField для интеграции с Formik
удаляем коммент

2024-02-25 15:59 UTC, aimenin commented on src/shared/ui/Checkbox/Checkbox.tsx
> +const Checkbox: FC<CheckboxProps> = ({ name, value, label, htmlFor }) => {
остальные пропсы checkbox где?
Посмотри как сделано в button с пропсами

2024-02-25 15:59 UTC, aimenin commented on src/stories/Configure.mdx
> -          href="https://storybook.js.org/docs/react/writing-tests/introduction"
почему изменена строчка?

2024-02-25 15:59 UTC, aimenin commented on src/widgets/FormReturn/FormReturn.tsx
> +import styles from './FormReturn.module.scss'
порядок импорта не соблюдается во всех новых файлах

2024-02-25 15:59 UTC, aimenin commented on src/widgets/FormReturn/FormReturn.tsx
> +import Label from '../../shared/ui/Label/Label'
из shared импортируем через @

2024-02-25 15:59 UTC, aimenin commented on src/widgets/FormReturn/FormReturn.tsx
> +export type TFormReturn = {
в компоненте типизируем только пропсы

2024-02-25 15:59 UTC, aimenin commented on src/widgets/HelpCategories/HelpCategories.tsx
> +const HelpCategories = () => {
нет документации

2024-02-25 15:59 UTC, aimenin commented on src/widgets/HelpCategories/HelpCategories.tsx
> +    <>
не нужен фрагмент

2024-02-25 18:31 UTC, Evgenii959 commented on src/stories/Configure.mdx
> -          href="https://storybook.js.org/docs/react/writing-tests/introduction"
Не знаю. Не менял. Может при установке пакета какого нибудь по ошибке. Без понятия...

2024-02-25 18:31 UTC, Evgenii959 commented
Исправил ошибки. Затушил.

2024-02-25 18:36 UTC, Evgenii959 commented
Лишние пр закрыл

2024-02-27 08:24 UTC, aimenin requested changes
Не выполнены некоторые замечания.
До сих пор нет понимания, что произошло со сторибуком.
Законченные обсуждения мы закрываем, если ты считаешь, что они выполнены

2024-02-27 08:24 UTC, aimenin commented on src/shared/ui/Checkbox/Checkbox.tsx
> +export interface CheckboxProps {
не выполнено

2024-02-27 08:24 UTC, aimenin commented on src/widgets/FormReturn/FormReturn.tsx
> +const FormReturn = () => {
нет документации

2024-02-27 08:24 UTC, aimenin commented on src/widgets/FormReturn/FormReturn.tsx
> +// @TODO: Сверстать форму возврата
причем здесь этот TODO

2024-02-27 08:24 UTC, aimenin commented on src/widgets/HelpCategories/HelpCategories.tsx
> +const HelpCategories = () => {
не выполнено

2024-02-27 08:24 UTC, aimenin commented on .storybook/main.ts
нет ответа почему изменен конфиг сторибука

2024-02-27 08:24 UTC, aimenin commented on .storybook/preview.ts
что это за файл

2024-02-27 08:24 UTC, aimenin commented on src/stories/Configure.mdx
> -          href="https://storybook.js.org/docs/react/writing-tests/introduction"
А зачем пакет был установлен?

2024-02-27 08:28 UTC, aimenin requested changes
Так же порядок импортов и их оформление делаем как в других файлах

2024-02-27 08:28 UTC, aimenin commented on src/widgets/FormReturn/FormReturn.tsx
> +import styles from './FormReturn.module.scss'
Как оформлять импорты можно посмотреть в других файлах

2024-02-28 14:07 UTC, Evgenii959 commented on src/shared/ui/Checkbox/Checkbox.tsx
> +export interface CheckboxProps {
Не понял вопроса. Смотрел как другие сделали, все также. У Артура спросил, тоже не знает)

2024-02-28 14:09 UTC, Evgenii959 commented on src/stories/Configure.mdx
> -          href="https://storybook.js.org/docs/react/writing-tests/introduction"
Удалил так как не знаю как это появилось, может команду не ту ввел. Вообщем вернул

2024-02-29 18:18 UTC, Evgenii959 commented
Исправил ошибки. То что было лишнее в сторибук удалил, не знаю откуда появилось.

2024-03-04 13:40 UTC, aimenin approved these changes
После того как разберешься со сторибук можно мержить будет, скорее всего был зарущен скрипт storybook init или что то подобное.
Разберись с дублированием конфига сторибука

2024-03-04 18:35 UTC, Evgenii959 commented
удалил .storybook

2024-03-05 13:15 UTC, aimenin commented
Можно мержить, после того как поправишь конфликты

2024-03-06 19:35 UTC, merged