#259-enhancement-hid-Blocks-on-MainPage
Studio-Yandex-Practicum/maxboom_frontend pull request #262
Opened 2024-03-11 19:16 UTC by JuliaAvramenko

Я сделала скрытие компонента в NewsBlock, BlogBlock, StoriesBlock.
В компонентах ReviewsBlock и BrandBlock возникает ошибка: 
![image](https://github.com/Studio-Yandex-Practicum/maxboom_frontend/assets/119536151/674d00ed-49fc-4c0e-815b-b340ac87fb21)

2024-03-18 14:36 UTC, aimenin requested changes
По поводу ошибки, пока не было времени посмотреть.
По коду написал, что можно улучшить

2024-03-18 14:36 UTC, aimenin commented on src/entities/BannerCard/BannerCard.stories.tsx
> +import BannerCard, { TBannerCard } from './BannerCard'
```suggestion
import BannerCard, { type TBannerCard } from './BannerCard'
```

2024-03-18 14:36 UTC, aimenin commented on src/widgets/BannerBlock/ui/BannerBlock.tsx
> +    return undefined
компонент не может возвращать undefined, он должен вернуть либо разметку либо null

2024-03-18 14:36 UTC, aimenin commented on src/widgets/BlogBlock/ui/BlogBlock.tsx
> +    return undefined
не возвращаем undefined из компонентов

2024-03-18 14:36 UTC, aimenin commented on src/widgets/BrandBlock/ui/BrandBlock/BrandBlock.tsx
> +    // brands.length !=0 &&
комментарий удаляем

2024-03-18 14:36 UTC, aimenin commented on src/widgets/ReviewsBlock/ui/ReviewsBlock/ReviewsBlock.tsx
> +    // reviews.length != 0 &&
удаляем комментарий, если не нужен

2024-04-02 11:25 UTC, JuliaAvramenko commented on src/entities/BannerCard/BannerCard.stories.tsx
> +import BannerCard, { TBannerCard } from './BannerCard'
Извини, не очень поняла, что нужно сделать

2024-04-02 11:29 UTC, aimenin approved these changes
👍

2024-04-02 11:34 UTC, merged