№251 info page contacts
Studio-Yandex-Practicum/maxboom_frontend pull request #264
Opened 2024-03-13 15:45 UTC by Evgenii959

Сделал контактную информацию и форму под картой в странице контакты

2024-03-14 14:09 UTC, aimenin requested changes
Делаем правильные ссылки + не очень понял почему изменен опять конфиг для сторибука

2024-03-14 14:09 UTC, aimenin commented on src/features/FormQuestion/ui/FormQuestion.tsx
> +    console.log('Ok')
console.log в main не мержим

2024-03-14 14:09 UTC, aimenin commented on src/pages/ContactsPage/ContactsPage.tsx
> +            <li>Maxboomofficial@yandex.ru</li>
на сайте это сделано в виде ссылки

2024-03-14 14:09 UTC, aimenin commented on src/pages/ContactsPage/ContactsPage.tsx
> +            <li>г. Москва</li>
Это не просто текст - это ссылка

2024-03-14 14:09 UTC, aimenin commented on src/widgets/FormReturn/model/validation/validation.ts
Почему здесь сделана валидация на странице возврата товара?
Этот pr относится к другой задаче, так мы делаем. Если нужно сделать, например, валидацию, делаем новый issue и делаем отдельно.
Это, мы конечно, оставим сейчас, но в будущем так не делаем

2024-03-16 17:13 UTC, Evgenii959 commented on package.json
> +    "leaflet": "^1.9.4",
Версия та же, переустанавливал

2024-03-17 17:19 UTC, Evgenii959 commented
установил @storybook/test так как просил для файла page.stories.tsx

2024-03-18 14:31 UTC, aimenin approved these changes
👍

2024-03-18 16:21 UTC, merged