Development 194 list category page
Studio-Yandex-Practicum/maxboom_frontend pull request #265
Opened 2024-03-13 19:31 UTC by Kseniya554

Сверстала страницу всех категорий. Моками не воспользовалась, повторила раз 10 элемент CategoryCard, мне это показалось проще. Использовала гриды для распределения карточек
По стилям всё вроде ок, единственное, не получается изменить стиль ссылки на главную страницу.
И поправила стили (округлила до целых)

2024-03-14 13:55 UTC, aimenin commented
Добавляем ссылку на задачу:
- Либо с помощью слова closes #номер_задачи
- Либо с помощью вкладки development справа

2024-03-14 13:57 UTC, aimenin requested changes
Используем нашу типографику

2024-03-14 13:57 UTC, aimenin commented on src/pages/CategoryPage/CategoryPage.tsx
> +      <h2 className={styles['category-page__title']}>Все категории</h2>
Используем наши компоненты из папки shared

2024-03-14 13:57 UTC, aimenin commented on src/pages/CategoryPage/CategoryPage.tsx
> +        <p> / Все категории</p>
Типографика из папки shared

2024-03-14 13:57 UTC, aimenin commented on src/widgets/CategoryCardList/CategoryCardList.tsx
> +export const CategoryCardList: FC = () => {
к каждому компоненту мы пишем документацию

2024-03-18 08:54 UTC, Kseniya554 commented on src/widgets/CategoryCardList/CategoryCardList.tsx
> +export const CategoryCardList: FC = () => {
Каким образом пишется документация? Имеешь ввиду комментарии? Или отдельный файл?

2024-03-18 08:56 UTC, Kseniya554 commented on src/widgets/CategoryCardList/CategoryCardList.tsx
> +import { FC } from 'react'
Тут надо прописать import type { FC } from 'react', правильно понимаю?

2024-03-18 08:57 UTC, Kseniya554 commented on src/widgets/CategoryCardList/CategoryCardList.tsx
> +// import Heading, { HeadingType } from '@/shared/ui/Heading/Heading'
Удалить закомментированный код?)

2024-03-18 14:29 UTC, aimenin commented on src/widgets/CategoryCardList/CategoryCardList.tsx
> +import { FC } from 'react'
Да

2024-03-18 14:30 UTC, aimenin commented on src/widgets/CategoryCardList/CategoryCardList.tsx
> +export const CategoryCardList: FC = () => {
Документация над компонентом, можно посмотреть как это сделано на других компонентах

2024-03-18 14:30 UTC, aimenin commented on src/widgets/CategoryCardList/CategoryCardList.tsx
> +// import Heading, { HeadingType } from '@/shared/ui/Heading/Heading'
Если он не нужен, то конечно, такое в main мы не тянем

2024-04-03 09:58 UTC, aimenin commented
1. Ссылки на задачу так и не появилось, не понятно, что решается в данном pr
2. Сейчас не понимаю с чем здесь можно помочь, если есть конкретный вопрос в чат в telegram

2024-04-06 15:11 UTC, merged