development-195-category-list-api
Studio-Yandex-Practicum/maxboom_frontend pull request #304
Opened 2024-04-15 19:16 UTC by Kseniya554

Ссылка на задачу https://github.com/Studio-Yandex-Practicum/maxboom_frontend/issues/195

2024-04-16 13:26 UTC, aimenin requested changes
Связки с api не обнаружено

2024-04-16 13:26 UTC, aimenin commented on src/entities/CategoryCard/CategoryCard.tsx
> +  // function getCatgoryCard() {
удаляем комментарии

2024-04-16 13:26 UTC, aimenin commented on src/entities/CategoryCard/getCategoryCard.tsx
> +function getCatgoryCard() {
Для использования api используем thunk-и. Данные храним в redux. Из redux данные достаем с помощью селекторов.

2024-04-18 15:40 UTC, Kseniya554 commented
Проблема в файле CategoryCard.tsx с функцией getCategoryCard в юзэффекте

2024-04-19 12:05 UTC, aimenin requested changes

2024-04-19 12:05 UTC, aimenin commented on src/entities/CategoryCard/CategoryCard.tsx
> +export const CategoryCard: FC<{ categoryCard: string }> = ({ categoryCard }) => {
CategoryCard просто рендерит категорию, в ней мы не делаем запрос за данными.
![image](https://github.com/Studio-Yandex-Practicum/maxboom_frontend/assets/49648795/fed32c9b-f407-47b0-bd2e-184b1cf6e52f)

Вот это ручка для получения списка категорий. Необходимо получить список категорий и отрендерить их

2024-04-19 12:05 UTC, aimenin commented on src/entities/CategoryCard/getCategoryCard.tsx
> +export const getCategoryCard = createAsyncThunk<TCategory, string, ThunkConfig<ApiError>>(
вижу только thunk, а где slice? Как данные попадают в стор?

2024-04-19 12:05 UTC, aimenin commented on src/entities/CategoryCard/types.tsx
> +export interface RootState {
тип RootState и тд у нас уже есть, посмотри как сделано в других компонентах. Тебе нужно сделать slice для категорий и с ним работать

2024-04-22 08:08 UTC, aimenin requested changes
Я чуть чуть не понял, что я должен здесь проверить.
Давай доделаем до конца и я тогда проверю твою работу

2024-04-22 08:08 UTC, aimenin commented on src/entities/CategoryCard/categorySlice.tsx
посмотри внимательнее структуру папок в fsd
в CategoryCard должна лежать папка model, где будут файлы, которые относятся к модели

Так же, расширение tsx - это для файлов react, где у нас есть jsx разметка.
Для этого файла расширение - ts

2024-04-29 15:54 UTC, aimenin requested changes
Насколько я вижу, практически готово, осталось подключить к глобальному стейту

2024-04-29 15:54 UTC, aimenin commented on src/entities/CategoryCard/CategoryCard.tsx
> +          {/* когда будут картинки в бэке, можно будет воспользоваться этой строчкой */}
в таких случаях - делаем issue, а здесь оставляем TODO + ссылку на этот issue

2024-04-29 15:54 UTC, aimenin commented on src/entities/CategoryCard/categorySlice.tsx
> +// import { apiErrorIdentify } from '@/shared/api/apiErrorIdentify';
удаляем не нужные комментарии

2024-04-29 15:54 UTC, aimenin commented on src/entities/CategoryCard/categorySlice.tsx
> +// Экспортируем редуктор среза
такие комментарии тоже удаляем

2024-04-29 15:54 UTC, aimenin commented on src/entities/CategoryCard/categorySlice.tsx
У тебя есть слайс, но я не вижу, чтобы он был подключен к глобальному стейту. Просмотри папку app -> providers, там будут подключены все слайсы к глобальному стейту, также там будут объявлен тип RootState, который нужно использовать.

2024-05-02 14:22 UTC, aimenin requested changes
Я не вижу, чтобы были исправлены мои комментарии

2024-05-06 10:20 UTC, aimenin approved these changes
👍

2024-05-13 09:29 UTC, merged