enhancement_333_sidebar_menu
Studio-Yandex-Practicum/maxboom_frontend pull request #334
Opened 2024-04-25 17:56 UTC by AlexanderMorugin

Сделано SideBarMenu, лежит в папке widgets. В storybook есть два компонента, оба находятся в папке widgets. Первый - это одна раскладывающаяся кнопка SideBar. Второй - SideBarMenu - это "Аккордеон" меню из таких кнопок. В готовом проекте, на компонент можно посмотреть вы папке pages -> FormReturnPage или запустить проект npm run start, затем в шапке сайта кликнуть "Помощь" -> "Возвраты"

2024-04-29 15:38 UTC, aimenin requested changes
Отличная работа, давай только добавим интерактивность с клавиатуры + переместим вложенный widget на другой уровень

2024-04-29 15:38 UTC, aimenin commented on src/widgets/SideBar/ui/SideBar.tsx
> +import { ISideBar } from '../model/types/types'
типизацию пропсов мы храним вместе с компонентом, тоесть, их можно писать над компонентом и экспортировать

2024-04-29 15:38 UTC, aimenin commented on src/widgets/SideBar/ui/SideBar.tsx
> +    <div onClick={onClick} className={styles.sideBar}>
Так же интерактивным элементам на основе div мы добавляем tabindex = 0 + делаем возможность интерацию с ними с клавиатуры

2024-04-29 15:38 UTC, aimenin commented on src/widgets/SideBarMenu/ui/SideBarMenu.tsx
> +              <SideBar isVisible={true} title={item.title}>
widget не может быть вложен в widget - нужно подумать куда его можно перенести

2024-04-30 15:11 UTC, AlexanderMorugin commented
- Исправил все замечания
- Компонент SideBar перенес из папки widgets в папку features
- Массив данных меню профиля перенес в папку mockData и назвал его sideBarProfileData.ts . Далее этот массив будет использоваться в модальном окне SideBarMenuModal

2024-05-02 14:19 UTC, aimenin approved these changes
👍

2024-05-02 14:38 UTC, merged