enhancement_308_header_categories_skeleton
Studio-Yandex-Practicum/maxboom_frontend pull request #337
Opened 2024-04-27 12:55 UTC by AlexanderMorugin

Задание:
- Скелетон в категориях header #308

Сделано:
- В папке shared/ui/CatalogLink создан компонент CatalogLinkSkeleton.tsx
- В папке entities/Category/slice, в слайсе categorySlice.ts, добавлен новый стейт isLoading
- В папке entities/Category/selectors, в файле categorySelectors.ts, добавлен новый экшен getLoading
- В папке widgets/Header, в компоненте Header.tsx, добавлена новая константа isCategoriesLoading и с ее помощью внедрен компонент CatalogLinkSkeleton, на время пока категории не загрузились с сервера

2024-04-29 15:28 UTC, aimenin requested changes
Отличная работа, но нужно чуть переделать скелетон ссылки, как - описал в комментариях

2024-04-29 15:28 UTC, aimenin commented on src/shared/ui/CatalogLink/model/skeleton/CatalogLinkSkeleton.tsx
Catalog Link Skeleton будет состоять из одной ссылки, сколько их рендерить мы решаем не в самом компонент скелетона, а непосредственно в компоненте применения скелетона.

2024-04-29 15:28 UTC, aimenin commented on src/shared/ui/CatalogLink/model/skeleton/CatalogLinkSkeleton.tsx
А почему у нас скелетон лежит в папке model? Skeleton - это ui, так что давай перенесем его в папку ui

2024-04-29 15:28 UTC, aimenin commented on src/widgets/Header/Header.tsx
> +                <CatalogLinkSkeleton />
вот здесь мы уже решаем, что отрендерим 4 штуки скелетона ссылок

2024-04-30 11:57 UTC, AlexanderMorugin commented
- Исправил замечания
- В файле header.module.scss добавил новый класс &__catalogLinkSkeleton

2024-05-02 14:18 UTC, aimenin approved these changes
Отличная работа!

2024-05-02 14:33 UTC, merged