#319-remove-product-from-cart
Studio-Yandex-Practicum/maxboom_frontend pull request #345
Opened 2024-05-04 09:11 UTC by JuliaAvramenko

2024-05-06 10:18 UTC, aimenin requested changes
1. Поправить селектор
2. Вынести функцию
3. Добавь, пожалуйста, блокировку кнопок увеличить, добавить и тд на время запроса. Чтобы мы жали на кнопку, например, уменьшить количество и в это время мы не могли нажать + или -, а иначе у нас может появится история, что один из запросов завалится и у нас будет что то не понятное на экране.

2024-05-06 10:18 UTC, aimenin commented on src/features/CartEdit/model/selectors.ts
> +export const isSuccessfulRequest = (state: StateSchema) => {
а у нас нет соглашения, что в селекторе должно присутствовать слово Selector? Что то типо:
isSuccessfulRequestSelector

2024-05-06 10:18 UTC, aimenin commented on src/features/CartEdit/model/selectors.ts
> +    state.productAmount.isIncreaseSuccessful ||
не очень понял этот селектор, если у нас пройдет запрос для Increase и не пройдет для Decrease, то селектор все равно будет успешным, потому что тут или стоит. Нужно подумать -  как это поменять

2024-05-06 10:18 UTC, aimenin commented on src/features/CartEdit/ui/CartEdit/CartEdit.tsx
> +              {productWithInfo.amount * Number(productWithInfo.product.price)} {productWithInfo.product.brand}
productWithInfo.amount * Number(productWithInfo.product.price) - вот это выносим в функцию, может понадобится где то еще

2024-05-13 14:16 UTC, JuliaAvramenko commented on src/features/CartEdit/model/selectors.ts
> +    state.productAmount.isIncreaseSuccessful ||
Данный селектор нужен для вызова useEffect для обновления корзины на действия по увеличению, уменьшению и удалению товара. Может быть это не лучший вариант , тут может быть в API, вероятно, оно не очень корректно разработано, так как возвращает нам количество продукта, но не обновленную корзину. Если у тебя есть мысли по поводу того, как это сделать лучше, то посоветуй.

2024-05-13 15:53 UTC, aimenin approved these changes
👍

2024-05-16 12:06 UTC, merged