enhancement_341_header_adaptive
Studio-Yandex-Practicum/maxboom_frontend pull request #346
Opened 2024-05-05 12:44 UTC by AlexanderMorugin

- Сделан адаптив хедера. Плавное сжатие до 1200px в ширину браузера. Далее хедер приобретает мобильный стиль. Теперь в десктопном режиме, хедер - грид, в мобильном - флекс. 

- На момент моей работы, проверить адаптивность при ширине 1200px возможно только если в компоненте RootPage.tsx закомментировать следующие компоненты, из за их неадаптивности:
<main className={styles.main}>
  <Outlet />
</main>
<Footer />

- В папке entities создал компонент кнопки мобильного меню HeaderMenuMobile и его сторибук.

- Внес изменения в компоненте entities -> HeaderAccount появления иконок под мобильный хедер.

- Далее в планах для мобильной версии сделать две модалки: Первая (большая) - меню, раскрывается при нажатии в шапке на кнопку меню (три полоски). Вторая модалка - поиск, раскрывается при нажатии на кнопку поиска (лупа)

2024-05-06 09:49 UTC, aimenin commented
Создай сразу issue для компонентов:
"main className={styles.main}"
" Outlet "
"main"

Нужно сделать и их адаптивными

2024-05-06 10:10 UTC, aimenin requested changes
Отличная работа! Парочка замечаний и не очень понял элемент HeaderMenuSign

2024-05-06 10:10 UTC, aimenin commented on src/assets/images/header/iconSearch.svg
А почему у нас две картинки iconSearch?

2024-05-06 10:10 UTC, aimenin commented on src/entities/HeaderAccount/HeaderAccount.tsx
> +                <p className={styles['header__cart-total']}>{total}</p>
не используем просто тег p - используем нашу типографику

2024-05-06 10:10 UTC, aimenin commented on src/entities/HeaderMenuSign/ui/HeaderMenuSign.tsx
> +const HeaderMenuSign: FC = () => {
не очень понял компонент, мб оставишь коммент над ним - что это такое

2024-05-06 12:00 UTC, AlexanderMorugin commented
- Исправил замечания

- Компонент HeaderMenuSign - это кнопка меню в шапке (из трех полосочек). Если лучше будет использовать картинку svg, заменю.

- Ишью по поводу адаптации main разместил

2024-05-07 10:13 UTC, aimenin approved these changes
👍

2024-05-08 10:18 UTC, merged