enhancement_350_adaptive_main_page
Studio-Yandex-Practicum/maxboom_frontend pull request #396
Opened 2024-05-22 13:35 UTC by AlexanderMorugin

2024-05-23 15:16 UTC, aimenin requested changes
Парочка замечаний

2024-05-23 15:16 UTC, aimenin commented on src/entities/ReviewCard/ui/ReviewCardFeedback/ReviewCardFeedback.tsx
> +          <span className={styles.reviewCardFeedback__span}>
Здесь не Subheading?

2024-05-23 15:16 UTC, aimenin commented on src/features/SubscribeForm/SubscribeForm.module.scss
> +  z-index: 5;
Давай сделаем константу, где мы будем хранить уровни z-index, например 5 штук. Чтобы потом не запутаться в z-index-ах

2024-05-23 15:16 UTC, aimenin commented on src/widgets/ArticleBlock/ui/ArticleBlock.tsx
> +    setIsActive(!isActive)
Когда мы ориентируемся на прошлое состояние state - то передаем в функцию колбек
```suggestion
    setIsActive(prev => !prev)
```

2024-05-23 15:16 UTC, aimenin commented on src/widgets/ReviewsBlock/ui/ReviewsBlock.tsx
> + * @param {string} title - загаловок контейнера
не вижу параметров в компоненте

2024-05-23 15:16 UTC, aimenin commented on src/widgets/ReviewsBlock/ui/ReviewsBlock.tsx
> +  const arrayThreeReviews = reviews.feedbacks.slice(0, 3)
3 и 2 выносим в константы - такие магические числа в коде лучше не оставлять, потому что потом не понятно, что они значат

2024-05-23 15:16 UTC, aimenin commented on src/widgets/ReviewsBlock/ui/ReviewsBlock.tsx
> +  const reviews = useSelector((store: StateSchema) => store.feedbacks)
(store: StateSchema) => store.feedbacks - выносим в отдельный селектор, который можно будет переиспользовать

2024-05-24 12:42 UTC, AlexanderMorugin commented
- Исправил все замечания

- Создал файл _z-index.scss для констант. Лежит здесь '@/shared/styles/utils/z-index'

- Сделал компонент кнопки LinkButton для перехода на страницу "Всех отзывов". Появляется в ленте отзывов, на главной, в конце прокрутки, при ширине экрана менее 768px. Лежит в entities. Имеет сторибук. 


Смотрим сайт все также комментируя в MainPage не сделанные компоненты, в соответствии с выше прикрепленной картинкой

2024-05-27 06:50 UTC, aimenin requested changes
Отличная работа! Парочка предложений по улучшению кода

2024-05-27 06:50 UTC, aimenin commented on src/widgets/BlogBlock/ui/BlogBlock.tsx
> +  const fourBlogArray = posts.slice(0, VIEW_FOUR_ITEMS)
Давай селектор постов и далее их преобразование вынесем в кастомный хук, положим его в папку с компонентом, в папку model

2024-05-27 06:50 UTC, aimenin commented on src/widgets/BrandBlock/ui/BrandBlock.tsx
> +import { Brand } from '../types/types'
типы лучше импортировать вот так:
```suggestion
import type { Brand } from '../types/types'
```

2024-05-27 06:50 UTC, aimenin commented on src/widgets/NewsBlock/ui/NewsBlock.tsx
> +  const fourNewsArray = news.slice(0, VIEW_FOUR_ITEMS)
news делаем так же как blog - выносим в отдельный хук

2024-05-27 06:50 UTC, aimenin commented on src/widgets/ReviewsBlock/ui/ReviewsBlock.tsx
> +  const ThreeReviewsArray = reviewArr.slice(0, VIEW_THREE_ITEMS)
здесь тоже в хук

2024-05-27 11:06 UTC, AlexanderMorugin commented on src/entities/AdvantageCard/ui/AdvantageCard.tsx
> +      <img src={image} alt={alt} className={styles.image} />
В shared есть такой компонент, но в нем стоит стиль .picture img {  
  width: 300% 
}, а зачем нам такой компонент здесь использовать?

2024-05-28 17:13 UTC, aimenin approved these changes
👍

2024-05-28 17:32 UTC, merged