#340-sidebar
Studio-Yandex-Practicum/maxboom_frontend pull request #398
Opened 2024-05-26 14:49 UTC by MargaritaShumilina

Сделал сайдбар, выглядит вот так:
![image](https://github.com/Studio-Yandex-Practicum/maxboom_frontend/assets/112693690/1edcb133-c156-4256-b3b7-f55939184fd8)

Активная ссылка подсвечивается, если она из подкатегорий, главная категория сразу открыта при переходе, чтобы отделить ее от остальных.

2024-05-26 14:50 UTC, MargaritaShumilina commented
Пришлось дополнить компонент Александра, но вроде ничего не сломала

2024-05-26 15:06 UTC, MargaritaShumilina commented
Ага, ага, не сломала :) Но вроде теперь все окей )

2024-05-27 04:53 UTC, aimenin requested changes
Отличная работа, парочка предложений по улучшению кода

2024-05-27 04:53 UTC, aimenin commented on src/features/CategoryItem/CategoryItem.tsx
> +  const [itemActive, setItemActive] = useState<MainCategoryInfo | BranchesData>()
Давай эти два стейта и useEffect вынесем в кастомный хук, откуда будем получать эти параметры.
Положить его можно в папку с этим же компонентом в models

2024-05-27 04:53 UTC, aimenin commented on src/features/CategoryItem/CategoryItem.tsx
> +        {item.branches.map(el => (
Может добавим проверку, что в item есть branches?

2024-05-27 04:53 UTC, aimenin commented on src/features/SideBar/ui/SideBar.tsx
> + * @param {string} to - если есть ссылка для item верхнего уровня, передает путь
Эти параметры я бы передавал объектом, так же еще я бы добавил флаг - раскрывающийся или нет это sidebar, чтобы было сразу понятно, как мы его используем

2024-05-30 09:22 UTC, MargaritaShumilina commented
Вынесла лишнее в хук, добавила проверку на наличие веток, перенесла все, что связано с сайдбаром категории в объект. А вот про флаг не поняла. У SideBar есть isVisible, как я поняла, как раз для того, чтобы выделить раскрывающийся список и нераскрывающийся. Или нужен какой-то другой флаг?

2024-05-30 11:26 UTC, aimenin approved these changes
Отлично, только одно маленькое замечание

2024-05-30 11:26 UTC, aimenin commented on src/features/SideBar/ui/SideBar.tsx
> +type TCategorySidebar = {
этот тип выносим в папку model, в папке с компонентом у нас только типизация компонента

2024-05-30 11:47 UTC, merged