Development 369 my account page
Studio-Yandex-Practicum/maxboom_frontend pull request #400
Opened 2024-05-30 17:03 UTC by kirill-k88

2024-06-03 07:31 UTC, aimenin requested changes
Отличная работа!
Парочка комментариев и вопросов

2024-06-03 07:31 UTC, aimenin commented on src/entities/Favorite/model/hooks/useFavorite.ts
> +import { IProduct } from '@/shared/model/types/ProductModel'
Такие импорты можно тоже через type импортировать

2024-06-03 07:31 UTC, aimenin commented on src/entities/HeaderAccount/HeaderAccount.tsx
> +  const logoutBtnHandle = () => {
я бы вынес это в хук, чтобы можно было переиспользовать в других компонентах, если у нас будет функциональность выхода из приложения в каком то другом компоненте

2024-06-03 07:31 UTC, aimenin commented on src/features/SideBarMenuModal/ui/SideBarMenuModal.tsx
> +      dispatch(logout())
вот здесь по сути используется тот же ход логаут, что и в компоненте выше.

2024-06-03 07:31 UTC, aimenin commented on src/features/login/model/services/getCurrentUser/getCurrentUser.ts
> +      if (axios.isAxiosError(error) && error.response && error.response.status === 401) {
вот здесь не очень понял логику, если у нас 401-я ошибка - мы выходим из приложения?
У нас рефреш токена нет?

2024-06-03 07:31 UTC, aimenin commented on src/pages/LogoutPage/LogoutPage.tsx
> +  const sideBar = useMemo(() => {
этот хук подходит только к этому компоненту?
Имею ввиду, это уникальная логика?

2024-06-03 07:31 UTC, aimenin commented on src/shared/model/types/ProductModel.ts
> +  price: string | number
ты вроде в другом компоненте использовал Nullable, давай будем последовательными и здесь тоже его заиспользуем

2024-06-03 07:31 UTC, aimenin commented on src/widgets/AccountCart/models/functions/functions.ts
> +export const getEndingByNumber = (number: number): string => {
Обрати внимание на вот эту апишку:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/PluralRules

2024-06-03 07:31 UTC, aimenin commented on src/widgets/LastOrder/LastOrder.tsx
> +      <div className={styles.lastOrder__footer}></div>
Если у нас пустой тег - то сразу его закрываем
```suggestion
      <div className={styles.lastOrder__footer} />
```

2024-06-03 07:31 UTC, aimenin commented on src/widgets/SideBarMenu/ui/SideBarMenu.tsx
> +      dispatch(logout())
вот здесь тоже повторяется код, как и в прошлых компонентах, для логаута из приложения

2024-06-03 07:31 UTC, aimenin commented on src/widgets/ProductsList/ProductsList.tsx
> +      label_hit={item.label_hit as boolean}
а почему здесь типизируется через as, не подтягиваются типы?

2024-06-03 17:05 UTC, kirill-k88 commented on src/pages/LogoutPage/LogoutPage.tsx
> +  const sideBar = useMemo(() => {
Это только тут используется. Но условную отрисовку компонентов внутри вынес в HOC

2024-06-03 17:06 UTC, kirill-k88 commented on src/entities/HeaderAccount/HeaderAccount.tsx
> +  const logoutBtnHandle = () => {
ОК, действительно, удобнее в отдельном хуке

2024-06-03 17:06 UTC, kirill-k88 commented on src/entities/Favorite/model/hooks/useFavorite.ts
> +import { IProduct } from '@/shared/model/types/ProductModel'
)

2024-06-03 17:06 UTC, kirill-k88 commented on src/features/login/model/services/getCurrentUser/getCurrentUser.ts
> +      if (axios.isAxiosError(error) && error.response && error.response.status === 401) {
Да, другой ручки нет

2024-06-03 17:11 UTC, kirill-k88 commented on src/widgets/ProductsList/ProductsList.tsx
> +      label_hit={item.label_hit as boolean}
Нужна отдельная задачка на приведение этого типа к единому варианту в проекте

2024-06-03 17:11 UTC, kirill-k88 commented on src/widgets/SideBarMenu/ui/SideBarMenu.tsx
> +      dispatch(logout())
Ага, переиспользовал хук

2024-06-04 04:56 UTC, kirill-k88 commented on src/widgets/AccountCart/models/functions/functions.ts
> +export const getEndingByNumber = (number: number): string => {
О, здорово! применил

2024-06-04 09:47 UTC, kirill-k88 commented on src/shared/model/types/ProductModel.ts
> +  price: string | number
так тут вроде не с null

2024-06-05 12:11 UTC, aimenin approved these changes
Отличная работа!

2024-06-05 14:48 UTC, merged